---
# Toutes les adaptations du groupe doivent etre faites ici.
# Ce fichier est volontairement simple et sert de point d'entree commun.

x-smartcity-common-env: &smartcity-common-env
  AIRFLOW_CONN_SENSOR_API: ${AIRFLOW_CONN_SENSOR_API:-http://api:8000}
  AIRFLOW_CONN_SMARTCITY_TIMESCALEDB: ${AIRFLOW_CONN_SMARTCITY_TIMESCALEDB:-postgresql://smartcity_user:smartcity_password@timescaledb:5432/smartcity}
  AIRFLOW_CONN_MINIO_LOCAL: ${AIRFLOW_CONN_MINIO_LOCAL:-aws://minio_admin:minio_password_2026@?endpoint_url=http%3A%2F%2Fminio%3A9000&region_name=us-east-1}
  _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-apache-airflow-providers-postgres apache-airflow-providers-amazon apache-airflow-providers-http httpx requests boto3 psycopg2-binary}

services:
  airflow-apiserver:
    environment:
      <<: *smartcity-common-env

  airflow-scheduler:
    environment:
      <<: *smartcity-common-env

  airflow-dag-processor:
    environment:
      <<: *smartcity-common-env

  airflow-worker:
    environment:
      <<: *smartcity-common-env

  airflow-triggerer:
    environment:
      <<: *smartcity-common-env

  airflow-init:
    environment:
      <<: *smartcity-common-env
